pipeline:
  build:
    image: java:openjdk-7
    pull: true
    
  publish:
    image: plugins/docker
    repo: abhisirohi/ZendeskProjectInternship
    #secrets: [ docker_username, docker_password ]
    # auto_tag: true
    debug: true
    tags: ${DRONE_COMMIT_SHA}
    dockerfile: Dockerfile-pretrain
    
  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: slack_test
    template: >
      Build #{{ build.number }} finished with a {{ build.status }} status. 
      Commit message: {{build.message}} - See more at {{system.link_url}}/{{repo.owner}}/{{repo.name}}/{{build.number}}
    
