pipeline:
  build:
    image: java:openjdk-7
    pull: true
    commands:
      - mvn clean
      - mvn install
      - mvn deploy
      
  notify:
    image: plugins/slack
    channel: devopsninjas
    username: abhishek.sirohi@domain.com.au

